image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master

build: off

install:

  - java -jar aqa-shop.jar -Dspring.datasource.url=jdbc:mysql://185.119.57.9:3306/app -Dspring.datasource.username=app -Dspring.datasource.password=pass &
  - sleep 15
  - java -jar aqa-shop.jar -Dserver.port=9090 -Dspring.datasource.url=jdbc:postgresql://185.119.57.9:5432/app -Dspring.datasource.username=app -Dspring.datasource.password=pass &
  - sleep 15


build_script:
  - gradlew npmInstall
  - chmod u+x gradlew
  - ./gradlew test -Dsql.url=jdbc:mysql://185.119.57.9:3306/app -Dselenide.headless=true
  - ./gradlew test -Dsql.url=jdbc:postgresql://185.119.57.9:5432/app -Dselenide.headless=true



services:
    - mysql
    - postgresql
   
