image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master

build: off

install:

  - java  -Dspring.datasource.url=jdbc:postgresql://185.119.57.9:5432/app -Dspring.datasource.username=app -Dspring.datasource.password=pas --server.port=9090 -jar aqa-shop.jar &
  - sleep 15
  - java  -Dspring.datasource.url=jdbc:mysql://185.119.57.9:3306/app -Dspring.datasource.username=app -Dspring.datasource.password=pas -jar aqa-shop.jar &
  - sleep 15



build_script:
  - chmod u+x gradlew
  - ./gradlew test -Dsql.url=jdbc:mysql://185.119.57.9:3306/app  -Dsql.http=http://localhost:8080 -Dselenide.headless=true
  - ./gradlew test -Dsql.url=jdbc:postgresql://185.119.57.9:5432/app -Dsql.http=http://localhost:9090 -Dselenide.headless=true



services:
  - mysql
  - postgresql
   
