image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:

  - java -jar aqa-shop.jar &


build_script:
  - chmod u+x gradlew
  - ./gradlew test --info -Dselenide.headless=true
  - ./gradlew allureServe

services:
    - mysql
   
