image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master
    - mySQL
    - postgres

build: off

install:
  - java  -Dspring.datasource.url=jdbc:postgresql://localhost:5432/app -Dspring.datasource.username=postgres -Dspring.datasource.password=Password12! -Dserver.port=9090 -jar aqa-shop.jar &
  - sleep 15
  - java  -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -Dspring.datasource.username=root -Dspring.datasource.password=Password12! -jar aqa-shop.jar &
  - sleep 15
  - npm install  --save file: gate-simulator/package.json


build_script:
  - chmod u+x gradlew
  - ./gradlew test -Dsql.url=jdbc:mysql://localhost:3306/app  -Dsql.http=http://localhost:8080 -Dselenide.headless=true
  - ./gradlew test -Dsql.url=jdbc:postgresql://localhost:5432/app -Dsql.http=http://localhost:9090 -Dselenide.headless=true
  - ./gradlew allureServe


services:
  - mysql
  - postgresql

test:
  categories:
    - Common    # A category common for all jobs