image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master

build: off

install:

  - java -jar aqa-shop.jar -Dspring.datasource.url=jdbc:postgresql://localhost:5432/app -Dspring.datasource.username=postgres -Dspring.datasource.password=password12 --server.port=9090 &
  - sleep 15
  - java  -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -Dspring.datasource.username=root -Dspring.datasource.password=password12 -jar aqa-shop.jar &
  - sleep 15



build_script:
  - chmod u+x gradlew
  - ./gradlew test -Dsql.url=jdbc:mysql://localhost:3306/root -Dselenide.headless=true
  - ./gradlew test -Dsql.url=jdbc:postgresql://localhost:5432/postgres -Dselenide.headless=true



services:
    - mysql
    - postgresql
   
