image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master
    - mySQL
    - postgres
build: off

services:
  - mysql

install:
  - java  -jar aqa-shop.jar &
  - sleep 15

build_script:
  - chmod u+x gradlew
  - ./gradlew test -Dselenide.headless=true
  - ./gradlew allureServe
  - ./gradlew npmInstall


#services:
#  - mysql

