image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master

build: off

install:

  - java -jar aqa-shop.jar -Dspring.datasource.url=jdbc:mysql://185.119.57.9:3306/app -Dspring.datasource.username=app -Dspring.datasource.password=pass &
  - java -jar aqa-shop.jar -Dspring.datasource.url=jdbc:postgresql://185.119.57.9:5432/app -Dspring.datasource.username=app -Dspring.datasource.password=pass &
  - sleep 15


build_script:
  - chmod u+x gradlew
  - ./gradlew test --info -Dselenide.headless=true
  - ./gradlew test -Dsql.url=jdbc:mysql://185.119.57.9:3306/app
  - ./gradlew test -Dsql.url=jdbc:jdbc:postgresql://185.119.57.9:5432/app
  - ./gradlew allureServe
  - gradlew npmInstall

services:
    - mysql
    - postgresql
   
