image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

environment:
  nodejs_version: "12"

branches:
  only:
    - master
    - mySQL
    - postgres

build: off

install:
  - cd gate-simulator
  - npm install nodejs@latest -g
  - npm install
  - npm start &
  - cd ..





build_script:
  - java  -Dspring.datasource.url=jdbc:postgresql://localhost:5432/postgres -Dspring.datasource.username=postgres -Dspring.datasource.password=Password12! -Dserver.port=9090 -jar aqa-shop.jar > test2.zip &
  - sleep 15
  - java  -Dspring.datasource.url=jdbc:mysql://localhost:3306/mysql -Dspring.datasource.username=root -Dspring.datasource.password=Password12! -jar aqa-shop.jar > test1.zip &
  - sleep 15
  - chmod u+x gradlew
  - ./gradlew test -Dsql.url=jdbc:mysql://localhost:3306/mysql  -Dsql.http=http://localhost:8080 -Dselenide.headless=true
  - ./gradlew test -Dsql.url=jdbc:postgresql://localhost:5432/postgres -Dsql.http=http://localhost:9090 -Dselenide.headless=true
  - ./gradlew allureServe


services:
  - mysql
  - postgresql

test:
  categories:
    - Common    # A category common for all jobs

artifacts:
    - path: test1.zip
    name: MyMySQL
    - path: test2.zip
    name: MyPostg