version: '3'
services:

  postgresdb:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
  node-app:
    build: gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'
